export const shopProducts = [{
    id: 1,
    title: "Travel Laptop Backpack",
    img: "img/bag-1.jpg",
    img2: "img/bag-1.jpg",
    price: 29.99,
    size: 15.6,
    category: "laptop",
    company: "MATEIN",
    info: "Travel Laptop Backpack,Business Anti Theft Slim Durable Laptops Backpack with USB Charging Port,Water Resistant College School Computer Bag for Women & Men Fits 15.6 Inch Laptop and Notebook - Grey",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 2,
    title: "Little America Backpack",
    img: "img/bag-2.jpg",
    img2: "img/bag-2.jpg",
    price: 99.99,
    size: 17,
    category: "casual",
    company: "Herschel",
    info: "Herschel Little America Backpack Deep Teal/Tan Synthetic Leather One Size",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 3,
    title: "Lowepro Fastpack",
    img: "img/bag-3.jpeg",
    img2: "img/bag-3.jpeg",
    price: 95.97,
    size: 12,
    category: "laptop",
    company: "Lowepro",
    info: "Lowepro Fastpack BP 250 AW II - A Travel-Ready Backpack for DSLR and 15 Laptop and Tablet.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 4,
    title: "Travel Hiking Backpack Daypack",
    img: "img/bag-4.jpg",
    img2: "img/bag-4.jpg",
    price: 20.99,
    size: 17,
    category: "hiking",
    company: "Venture Pal",
    info: "This Venture Pal Backpack is made with high quality tear and water resistant material, provides extra strength and long-lasting performance with the lightest weight possible.",
    inCart: false,
    count: 0,
    total: 0
  },

  {
    id: 5,
    title: "Kanken Classic Backpack",
    img: "img/bag-5.jpeg",
    img2: "img/bag-5.jpeg",
    price: 105,
    size: 14.9,
    category: "casual",
    company: "Fjallraven",
    info: "ame classic Kanken design since 1978. Stash everyday essentials in the main zippered compartment, front zippered pocket, and two open side pockets.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 6,
    title: "Borealis Backpack",
    img: "img/bag-6.jpeg",
    img2: "img/bag-6.jpeg",
    price: 117.99,
    size: 16.8,
    category: "hiking",
    company: "The North Face",
    info: "Leave all the backpack drama at home. The sleek and functional Borealis by The North Face® is free of embellishment so you can grab your gear and go.",
    inCart: false,
    count: 0,
    total: 0
  },

  {
    id: 7,
    title: "KROSER Laptop Backpack",
    img: "img/bag-7.png",
    img2: "img/bag-7.png",
    price: 33.99,
    size: 15.6,
    category: "laptop",
    company: "KROSER",
    info: "KROSER Laptop Backpack 15.6 Inch Stylish Computer Backpack School Backpack Casual Daypack Laptop Bag Water Repellent Nylon Business Bag Tablet With USB Port for Travel/Business/College/Women/Men-Black",
    inCart: false,
    count: 0,
    total: 0
  },

  {
    id: 8,
    title: "AmazonBasics Classic Backpack",
    img: "img/bag-8.png",
    img2: "img/bag-8.png",
    price: 17.82,
    size: 15.8,
    category: "casual",
    company: "AmazonBasics",
    info: "Lightweight, durable backpack featuring adjustable padded shoulder straps and convenient side water bottle pockets.",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 9,
    title: "LLVS",
    img: "img/bag-9.jpg",
    img2: "img/bag-9.jpg",
    price: 196,
    size: 14,
    category: "casual",
    company: "LLVS",
    info: "LLVS Women's Monogram Reverse Palm Springs Backpack (Made in France)",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 10,
    title: "Cycling Hiking Backpack",
    img: "img/bag-10.jpeg",
    img2: "img/bag-10.jpeg",
    price: 22.99,
    size: 15.7,
    category: "hiking",
    company: "Sunhiker",
    info: "Sunhiker Cycling Hiking Backpack Water Resistant Travel Backpack Lightweight Small Daypack M0714",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 11,
    title: "Tocode Laptop Backpack",
    img: "img/bag-11.png",
    img2: "img/bag-11.png",
    price: 37.99,
    size: 17.3,
    category: "laptop",
    company: "Tocode",
    info: "Laptop Backpack, Tocode Travel Backpack Contains Multi-Function Pockets,Stylish Anti-Theft School Bag with USB Charging Port Fits 17.3 Inch Laptop Comfort Pack for Men & Women –Black Update",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 12,
    title: "Tactical Backpacks",
    img: "img/bag-12.png",
    img2: "img/bag-12.png",
    price: 39.99,
    size: 16.2,
    category: "hiking",
    company: "Mardingtop",
    info: "Mardingtop 25L/28L/35L Tactical Backpacks Molle Hiking daypacks for Camping Hiking Military Traveling",
    inCart: false,
    count: 0,
    total: 0
  }
];

export const detailProduct = {
  id: 1,
  display: true,
  title: "Travel Laptop Backpack",
  img: "img/bag-1.jpg",
  img2: "img/bag-1.jpg",
  price: 29.99,
  size: 15.6,
  category: "laptop",
  company: "MATEIN",
  info: "Travel Laptop Backpack,Business Anti Theft Slim Durable Laptops Backpack with USB Charging Port,Water Resistant College School Computer Bag for Women & Men Fits 15.6 Inch Laptop and Notebook - Grey",
  inCart: false,
  count: 0,
  total: 0
};